version: '3.8'

services:
  gdelt-dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./google_credentials.json:/app/google_credentials.json:ro
      - ./.env:/app/.env:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
    restart: unless-stopped 